### ISSUE TITLE
Both CrysFML and GSASII calculators failed to work with minimization

### ISSUE THREAD

**Issue by rozyczko** [easyScience/easyDiffractionApp#120]
**Issue 1**:
```
AttributeError: 'Site' object has no attribute 'Uiso'
```

**Issue 2**
Additionally, changing a parameter value when CrysFML is chosen gives
```
'NoneType' object has no attribute 'strip'
```

**Comment by rozyczko** [comment]
Both of these issues have workarounds:
1: https://github.com/easyScience/easyDiffractionLib/commit/19b97b866781e3564c87ff4b9e03150b99804a35
2: https://github.com/easyScience/easyCore/commit/f7ffdb85d68a5758180ca5a43116738989a680ad

**Comment by AndrewSazonov** [comment]
There are no more errors, but the minimisation with CrysFML or GSASII still doesn't work. And it remains broken even after switching back to CrysPy.

**Comment by rozyczko** [comment]
This has been fixed by implementing a larger numerical differentiation step for `CrysFML` and `GSASII` and changing the default method to `least_square`. This method allows the step to be adjusted.
The problem is with the fact that `CrysFML` uses a 32 bit float to store cell parameters and it runs out of precision when applied the default, very small step by `lmfit`.

The correct fix is to have CrysFML use double precision values for cell parameters, but we should also be prepared to support calculators which can't be modified.
