### ISSUE TITLE
Change license to BSD-3

### ISSUE THREAD

**Issue by rozyczko** [easyScience/easyDiffractionApp#23]
Make sure easyScience and dependants are BSD-3 compliant, as discussed at the group meeting and as agreed on for other ESS software projects.

**Comment by rozyczko** [comment]
ChemDoodle Web Components are distributed under GPL 3.0.
The viral nature of GPL means we can't easily turn BSD-compliant if we link to ChemDoodle.
https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

**Comment by rozyczko** [comment]
We might need to start thinking about replacing ChemDoodle with some other component, even if it isn't open source/free, if it gives us the freedom of using our licensing.

**Comment by AndrewSazonov** [comment]
It would be hard to find something to replace ChemDoodle. I checked out a number of JavaScript libraries capable of plotting crystal structure, and this was the only solution that was easy to use. ChemDoodle could be used as a basic structure viewer both within easyDiffraction and for an exported interactive html report.

Maybe we could contact iChemLabs? Their website says: [The ChemDoodle Web Components library is licensed under version 3 of the GNU GENERAL PUBLIC LICENSE. If you want to include ChemDoodle Web Components in your product or website, you must abide by this license, or contact us for a proprietary license.](https://web.chemdoodle.com/installation/license)

**Comment by rozyczko** [comment]
Working on getting the commercial license for ChemDoodle WCs library.

**Comment by AndrewSazonov** [comment]
Another note about QtCharts according to https://doc.qt.io/qt-5/qtcharts-index.html: 
Qt Charts is available under commercial licenses from The Qt Company. In addition, it is available under the GNU General Public License, version 3. See Qt Licensing for further details.

**Comment by AndrewSazonov** [comment]
easyDiffractionApp is based on easyCore, which has 3 minimizers. One of them is DFO-LS -- Derivative-Free Optimizer for Least-Squares with **GPL v3** type licence: https://github.com/numericalalgorithmsgroup/dfols

**Comment by rozyczko** [comment]
It is quite more complex than that.
https://www.gnu.org/licenses/gpl-faq.en.html
answers most of the questions.

1. Our own code can and should be BSD, just like ESS prefers.
2. The aggregate (what we distribute as full installation) can contain various licensed modules, GPL, BSD, Apache etc.
3. This aggregate will have to be of the most restrictive **compatible** license type, likely GPL-v3.
4. BSD is GPL compatible so we are fine here https://www.gnu.org/licenses/gpl-faq.en.html#OrigBSD
4. We need to specify modules used and relevant licensing

> I have written an application that links with many different components, that have different licenses. I am very confused as to what licensing requirements are placed on my program. Can you please tell me what licenses I may use? (#ManyDifferentLicenses)
To answer this question, we would need to see a list of each component that your program uses, the license of that component, and a brief (a few sentences for each should suffice) describing how your library uses that component. Two examples would be:

>> To make my software work, it must be linked to the FOO library, which is available under the Lesser GPL.
My software makes a system call (with a command line that I built) to run the BAR program, which is licensed under “the GPL, with a special exception allowing for linking with QUUX”

(from the GPL FAQ)

So, both _ChemDoodle_ and _QtCharts_ are fine being GPL - we don't need commercial versions of those.
On the other hand, the source of DFO-LS which we included is a much bigger concern.

One solution is to make it an external library - compile as a separate .pyd and link to it.
This way, our code is still BSD.

**Comment by rozyczko** [comment]
One important task here is to go through all the dependent modules and assure their licenses are BSD-compatible.
Otherwise we will have to replace those modules.

**Comment by rozyczko** [comment]
running updated FOSSA check on the released version would be necessary as well.

**Comment by rozyczko** [comment]
In a fashion similar to what @wardsimon did in easyCore, we should tag each source file in `easyDiffractionLib` and `easyDiffractionApp` with the SPDX identifier, e.g.

```
#  SPDX-FileCopyrightText: 2021 European Spallation Source <info@ess.eu>
#  SPDX-License-Identifier: BSD-3-Clause
```

Adding BSD license file (replacing the existing GPL file) is also needed.

**Comment by rozyczko** [comment]
`DFO-LS` is GPL-3 but we only use it as a module. This means the wrapper in easyCore\easyCore\Fitting\DFO_LS.py can also be BSD-licensed, and it should.

`pymatgen` is MIT-licensed, and MIT is BSD-compliant.

This means we can claim our whole source code is BSD compliant and change the official LICENSE.txt file.
