### ISSUE TITLE
Automated tutorial creation on Windows (running eD in test mode) fails (never finishes)

### ISSUE THREAD

**Issue by rozyczko** [easyScience/easyDiffractionApp#90]

**Comment by rozyczko** [comment]
- installed `easyDiffraction_Windows_x86-32_v0.8.0-beta.1.exe` to default location
- ran `poetry run python tools\Scripts\RunApp.py --testmode` from a build distribution (branch `updater`)
- the test run succeeded

Will have a look at the github runner

**Comment by rozyczko** [comment]
https://stackoverflow.com/questions/64813927/how-do-i-start-a-windows-gui-app-with-a-github-self-hosted-action-runner
seems vaguely relevant.

> Due to Windows session isolation, your user account can only see applications in its logon session, but not applications in other users' sessions (the GitHub action agent runs in just another session if you installed it as a service)

On the other hand, running `RunApp.py` happens in the same process/instance as the build.

**Comment by rozyczko** [comment]
This used to work before, stopped at some point recently.
Additionally, easyReflectometry tutorial generation works well on GH runners

**Comment by rozyczko** [comment]
potentially: comment out the windows icon?

**Comment by AndrewSazonov** [comment]
Commenting out the windows icon in main.py doesn't help.

**Comment by rozyczko** [comment]
Fixed by ensuring enough time for the operations and that the calculators are packaged...

**Comment by rozyczko** [comment]
fixed and merged
